version: '3.8'
services:

  backend:
    build: .
    ports:
      - '8080:8080'

  database:
    image: mysql:8.0.31
    environment:
      MYSQL_ROOT_PASSWORD: 'pass_00'
      MYSQL_DATABASE: 'video_stream'
    ports:
      - '3307:3306'