version: '3.8'
services:

  backend-web:
    build: .
    ports:
      - "8080:8080"
#    volumes:
#      - ./:/app
    depends_on:
      - database
  
  database:
    image: mysql:8.0.28
    environment:
      MYSQL_DATABASE: 'video_stream'
      MYSQL_USER: 'springuser'
      MYSQL_PASSWORD: 'pass_00'
      MYSQL_ROOT_PASSWORD: 'pass_00'
    ports:
      - '3307:3307'
    expose:
      - '3307'