version: '3.8'
services:

  database:
    image: mysql:8.0.31
    environment:
      MYSQL_ROOT_PASSWORD: 'pass_00'
      MYSQL_DATABASE: 'video_stream'
    ports:
      - '3307:3306'
    volumes:
      - ./mysqldata:/var/lib/mysql

  backend:
    build: back-app/back-app/
    ports:
      - '8080:8080'
    volumes:
      - ./back-app/back-app:/back-app
      - ./VideoStreamData:/VideoStreamData
    depends_on:
      - database

  frontend:
    build: front-app/front-app/
    ports:
      - '3000:3000'
    volumes:
      - ./front-app/front-app:/front-app
    depends_on:
      - backend
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - database
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - 8081:80
    depends_on:
      - frontend
  
  proxy:
    build: nginx/
    ports:
      - 8082:80
      # - 8083:90
    depends_on:
      - frontend
    # volumes:
    #   - ./nginx/src:/usr/share/nginx/html