version: '3.8'
services:

  database:
    image: mysql:8.0.31
    environment:
      MYSQL_ROOT_PASSWORD: 'pass_00'
      MYSQL_DATABASE: 'video_stream'
    ports:
      - '3307:3306'
    volumes:
      - ./mysqldata:/var/lib/mysql

  backend:
    build: production-dockerfiles/back-app/.
    ports:
      - '8080:8080'
    volumes:
      - ./VideoStreamData:/VideoStreamData
    depends_on:
      - database

  frontend:
    build: production-dockerfiles/front-app/.
    ports:
      - '3000:3000'
    depends_on:
      - backend