version: '3.8'
services:

  database:
    image: mysql:8.0.31
    environment:
      MYSQL_ROOT_PASSWORD: 'U6SS&iQaFPVwSF@%'
      MYSQL_DATABASE: 'video_stream'
    ports:
      - '3307:3306'
    volumes:
      - ./mysqldata:/var/lib/mysql

  backend:
    build: back-app/
    ports:
      - '8080:8080'
    volumes:
      - ./VideoStreamData:/VideoStreamData
    depends_on:
      - database

  # frontend:
  #   build: front-app/
  #   ports:
  #     - '3000:3000'
  #   depends_on:
  #     - backend